export const easyFruits = [
  "apple",
  "banana",
  "cherry",
  "grape",
  "kiwi",
  "lemon",
  // "elderberry",
  // "fig",
  // "honeydew",
  // "date",
  // "mango",
  // "nectarine",
  // "orange",
  // "papaya",
  // "quince",
  // "raspberry",
  // "strawberry",
  // "tangerine",
  // "watermelon",
];
